import { LegalDocument, DocumentAnalysis, Language } from '../types';

export function generatePDF(
  document: LegalDocument,
  analysis: DocumentAnalysis,
  language: Language
): Promise<boolean> {
  return new Promise((resolve) => {
    // Create printable citizen report window
    const printWindow = window.open('', '_blank', 'width=900,height=800');
    if (!printWindow) {
      resolve(false);
      return;
    }

    const summaryText = analysis.summary[language] || analysis.summary.en;

    const attentionRows = analysis.attentionItems.map(item => `
      <div style="border-left: 4px solid ${item.severity === 'HIGH ATTENTION' ? '#E11D48' : item.severity === 'REVIEW' ? '#F59E0B' : '#10B981'}; padding: 12px; margin-bottom: 12px; background: #F8FAFC; border-radius: 4px;">
        <div style="font-weight: bold; font-size: 14px; color: #0F172A;">
          [${item.severity}] ${item.title[language] || item.title.en} (Page ${item.evidencePage})
        </div>
        <p style="margin: 6px 0; color: #334155; font-size: 13px;">${item.shortExplanation[language] || item.shortExplanation.en}</p>
        <p style="margin: 4px 0; font-size: 12px; color: #1E40AF;"><strong>Recommended Action:</strong> ${item.recommendedAction[language] || item.recommendedAction.en}</p>
      </div>
    `).join('');

    const partiesRows = analysis.parties.map(p => `
      <div style="padding: 8px 12px; background: #F1F5F9; border-radius: 4px; margin-bottom: 6px; font-size: 13px;">
        <strong>${p.name}</strong> — <em>${p.role}</em> ${p.idNumber ? `(${p.idNumber})` : ''}
      </div>
    `).join('');

    const checklistRows = analysis.citizenChecklist.map(chk => `
      <li style="margin-bottom: 8px; font-size: 13px; color: #1E293B;">
        <strong>${chk.title}</strong>: ${chk.description}
      </li>
    `).join('');

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>LegalLingo Citizen Summary - ${document.filename}</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.5; color: #1E293B; margin: 30px; }
          h1 { color: #1E3A8A; font-size: 22px; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px; }
          h2 { color: #0F172A; font-size: 16px; margin-top: 20px; border-bottom: 1px solid #CBD5E1; padding-bottom: 4px; }
          .header-meta { font-size: 12px; color: #64748B; margin-bottom: 20px; }
          .badge { display: inline-block; padding: 4px 10px; background: #EFF6FF; color: #1E40AF; border-radius: 9999px; font-weight: bold; font-size: 12px; }
          .disclaimer { margin-top: 40px; padding: 12px; background: #FFFBEB; border: 1px solid #FDE68A; border-radius: 6px; font-size: 11px; color: #92400E; }
          @media print {
            body { margin: 15mm; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <h1>LegalLingo Citizen Document Summary</h1>
          <span class="badge">Health Score: ${analysis.healthScore}/100</span>
        </div>
        <div class="header-meta">
          <strong>Document:</strong> ${document.filename} | <strong>Type:</strong> ${document.documentType} | <strong>Exported:</strong> ${new Date().toLocaleDateString('en-IN')}
        </div>

        <h2>Executive Plain Language Summary</h2>
        <p style="background: #EFF6FF; padding: 14px; border-radius: 6px; font-size: 14px; border-left: 4px solid #2563EB;">${summaryText}</p>

        <h2>Parties to the Contract</h2>
        ${partiesRows}

        <h2>Financial Summary</h2>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 13px;">
          <tr style="border-bottom: 1px solid #E2E8F0;"><td style="padding: 6px 0;"><strong>Total Value:</strong></td><td>${analysis.financialDetails.totalAmount || 'N/A'}</td></tr>
          <tr style="border-bottom: 1px solid #E2E8F0;"><td style="padding: 6px 0;"><strong>Advance Paid:</strong></td><td>${analysis.financialDetails.advancePaid || 'N/A'}</td></tr>
          <tr style="border-bottom: 1px solid #E2E8F0;"><td style="padding: 6px 0;"><strong>Balance Due:</strong></td><td>${analysis.financialDetails.balanceDue || 'N/A'}</td></tr>
          <tr style="border-bottom: 1px solid #E2E8F0;"><td style="padding: 6px 0;"><strong>Stamp Duty / Reg:</strong></td><td>${analysis.financialDetails.stampDuty || 'N/A'}</td></tr>
        </table>

        <h2>Critical Items Requiring Citizen Verification</h2>
        ${attentionRows}

        <h2>Pre-Signing Action Checklist</h2>
        <ul>${checklistRows}</ul>

        <div class="disclaimer">
          <strong>Citizen Legal Notice:</strong> This summary was generated by LegalLingo for educational and comprehension purposes. It does not constitute formal legal representation.
        </div>
      </body>
      </html>
    `;

    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();

    // Auto trigger print after render
    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
      resolve(true);
    }, 500);
  });
}
