"""Chat request/response schemas for POST /api/chat.

Never exposed to the LLM directly — used only to validate the
HTTP request body and shape the HTTP response.
"""
from typing import Optional

from pydantic import Field, field_validator

from app.schemas.base import CamelModel
from app.schemas.common import Language


class ChatRequest(CamelModel):
    """Body of POST /api/chat."""

    document_id: str = Field(..., min_length=1, description="ID of the document to query.")
    question: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Citizen's natural-language question about the document.",
    )
    language: Language = Field(
        default="en",
        description="Desired response language: 'en' (English), 'hi' (Hindi), 'mr' (Marathi).",
    )
    clause_id: Optional[str] = Field(
        default=None,
        description="Optional: ID of a specific clause to focus the answer on.",
    )

    @field_validator("question")
    @classmethod
    def _sanitise_question(cls, v: str) -> str:
        """Reject questions that are suspiciously long or contain obvious injection patterns."""
        dangerous = ["ignore previous instructions", "system prompt", "disregard your"]
        lower = v.lower()
        for pattern in dangerous:
            if pattern in lower:
                raise ValueError(
                    "Question contains disallowed content. Please ask a genuine question about your document."
                )
        return v.strip()


class ChatResponse(CamelModel):
    """Response from POST /api/chat."""

    answer: str = Field(..., description="Plain-language answer in the requested language.")
    evidence: str = Field(
        default="",
        description="Direct quote from the document supporting the answer (may be empty).",
    )
    page_number: Optional[int] = Field(
        default=None,
        ge=1,
        description="Page number the answer references (if available).",
    )
    clause_number: Optional[str] = Field(
        default=None,
        description="Clause number the answer references (if available).",
    )
    language: Language = Field(..., description="Language of the answer.")
    llm_used: bool = Field(
        default=False,
        description="True when the answer was generated by the LLM. False for deterministic fallback.",
    )
